# Conclusion

In this bookdown, we carefully examine the 2017 Citywide Mobility Survey launched by Department of Transportation of New York City. We have discovered many interesting patterns affecting residents' choices of transportation. We identified that even though bicycles are percepted as unsafe, people would use bicycles to travel around because of its inexpensiveness and convenience, especially male. We identified that owning a house in NYC, having children and living longer in the city would greatly increase the possibility of leaning towards cars. We later recognized that living in different boroughs affects their preferences a lot. We also identified that besides these socialeconomic factors, people's lifestyle also affects their preferences, especially if they order takeout food. We argued that this is majorly because they are more willing to embrace new technologies, and therefore has a higher preference for ride hailing services such as Uber. Finally, we carefully analyzed why people started to use these ride hailing services. The percentage of people using these are below our expectation, which also indicates space for growth. They are treated differently in different boroughs, with most frequently in Manhattan and least frequently in Staten Island; young people also seem to prefer this more than elder people, though for those great than 65 years old, over 30% of them still takes ride hailing trips a few times a month. 

As this survey is conducted annually, future analysis can be conducted on the changing trend of choices of transportation across years as soon as new data is made public ; especially in 2018 and 2019, more people started to use Uber and Lyft, and this may cause an interesting shift of perferences. 

In this analysis, we have worked hard on cleansing the data and filtering the variables we are interested in. Structuring the data clearly makes our further analysis really easier. This is probably the one lesson we have learned from this project. 